
from pathlib import Path
import pandas as pd 
import transformers
import torch
from transformers import AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report


path = Path.cwd() / "texts" / "hansard500.csv"
df = pd.read_csv(path)

#print(df.head())
#print(df.columns)

#print(df.shape)

# rename the ‘Labour (Co-op)’ value in ‘party’ column to ‘Labour’
df["party"] = df["party"].replace("Labour (Co-op)", "Labour")

# print(df["party"].value_counts().head(10))

party_labels = ["Conservative", "Labour", "Liberal Democrat", "Scottish National Party"]

def clean_predictions(raw_output):      # If the model returns more than one label this function 
    raw_output = raw_output.strip()     # chooses the first one
    
    found_labels = []
    
    for label in party_labels:
        position = raw_output.find(label)
        if position != -1:
            found_labels.append((position, label))
            

    if found_labels:
        found_labels.sort()
        return found_labels[0][1]
        
    return "Unknown"
    
    
# keep only the same four party labels used in Part Two
df = df[df["party"].isin(party_labels)]
# print(df["party"].value_counts().head(10))

# Removing any rows where the value in the speech_class column is not "Speech"
df = df[df["speech_class"] == "Speech"]
# print(df["speech_class"].value_counts())

# Separating the training data and the labels
X = df["speech"]
y = df["party"]

# Creating the data for training with the random seed 26
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=26)
max_speech_char = 1500 

# printing the training labels
# print(y_train.value_counts())

# printing the testing labels
# print(y_test.value_counts())



# ZERO-SHOT PROMPTING SECTION for 3b)
# I first tested the HuggingFaceTB/SmolLM2-360M-Instruct which was easier to run as it is smaller but the outputs were really strange. It sometimes returned empty answers or it did not consistently return one party label.
# Then, I tested the HuggingFace zero-shot classification pipeline with tasksource/deberta-small-long-nli, but I did not use it for the final result as I realised it is not the right model for this task.
# Here I used the microsoft/Phi-4-mini-instruct model seen in the lab. This is a text generation model so it is suitable for prompting.
# The model was accessed through HuggingFace Transformers using transformers.pipeline("text-generation").
# I used AutoTokenizer to load the tokenizer for the model.
# The final working version loads the model directly inside the pipeline using model=model_name.
# The parameters I used:
# dtype = torch.bfloat16 to reduce memory usage since the model is large.
# device = -1 forces the model to run on CPU. I used this because device_map="auto" caused meta tensor/offloading errors on my machine.
# max_new_tokens = 10 is used because the model only needs to generate a short party label.
# do_sample = False makes the predictions deterministic rather than random.
# return_full_text = False returns only the answer generated by the model rather than the full prompt.

model_name = "microsoft/Phi-4-mini-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

generator = transformers.pipeline("text-generation", model = model_name, tokenizer = tokenizer, dtype = torch.bfloat16, device = -1)

zero_shot_predictions = []
true_labels = []

system_message = "You are a helpful assistant. Give short answers." 

for i, speech in enumerate(X_test):
    speech = speech[:max_speech_char]
    
    instruction = f"""
    Classify the following UK parliamentary speech by political party of the speaker.

    Choose exactly one of these four labels:

    Conservative
    Labour
    Liberal Democrat
    Scottish National Party
    
    Use evidence from the speech itself. Do not explain your answer.
    
    Speech:
    {speech}

    Party label:
    """

    prompt = f"<SYS> {system_message} <INST> {instruction} <RESP> "

    response = generator(prompt, max_new_tokens = 10, do_sample = False, return_full_text = False, clean_up_tokenization_spaces = False)
    
    raw_output = response[0]["generated_text"]

    predicted_label = clean_predictions(raw_output)
    zero_shot_predictions.append(predicted_label)
    true_labels.append(y_test.iloc[i])
    
    # print(raw_output)
    # print(predicted_label)
    # print(y_test.iloc[i])
    
print(f1_score(true_labels, zero_shot_predictions, labels=party_labels,  average="macro", zero_division=0))
print(classification_report(true_labels, zero_shot_predictions, labels = party_labels, zero_division=0))






#FEW-SHOT PROMPTING SECTION for 3c)
# In this section I used the same model but changed the prompt so that it includes labelled examples from the training data.
# This is different to the previous section as here the model is given examples of the task before it classifies the new speech.
# The prompt can be seen in the code below.
# I selected one example from each political party soo that the prompt contain one of each. I went over all the speeches and I chose
# the first one from every category/party to have one of each.
# Each example was shortened to the first 600 characters
# The test speeches were also shortened to the first 1500 characters. I also tried with 3000 but it did not improve f1 score.
# The predictions are cleaned using the clean_prediction function as the model returns more characters than just the party.
# The model was instructed to output only one of the four party labels.


# making a few-shot examples
max_example_char = 600  # it will be used to limit the length of each example speech

train_df = pd.DataFrame(        # Creating a dataframe with the speeches and the labels
    {"speech": X_train, 
    "party": y_train})

few_shot_examples = []

for label in party_labels:
    
    example = train_df[train_df["party"] == label].iloc[0]  
    example_speech = example["speech"][:max_example_char]    # keeping only the first 600 characters from the speeches selected for each party
    example_party = example["party"]    # the correct label 
    
    few_shot_examples.append((example_speech, example_party))   # Here we basically take the first available example for each party

# for example_speech, example_party in few_shot_examples:
    # print(example_party)


examples_text = ""
for example_speech, example_party in few_shot_examples:    # Creating a format for the few-shots examples text
    examples_text += f"""
    Example speech: {example_speech}
    
    Party label:
    {example_party}
    """
    
# print(examples_text)

few_shot_predictions = []               # these lists will store the few shot predictions
few_shot_true_labels = []               # and the correct labels

for i, speech in enumerate(X_test):
    speech = speech[:max_speech_char]
    
    instruction = f"""
    You are classifying UK parliamentary speeches by the political party of the speaker.

    Choose exactly one of these four labels and nothing else:

    Conservative
    Labour
    Liberal Democrat
    Scottish National Party
    
    The labelled examples below show the format of the task. 
    The examples are only provided to show how the task should be answered.
    Classify the new speech using only the content of the new speech.
    
    Labelled examples:
    
    {examples_text}

    Now classify this new speech:
    
    Speech:
    {speech}

    Party label:
    """

    prompt = f"<SYS> {system_message} <INST> {instruction} <RESP> "

    response = generator(prompt, max_new_tokens = 10, do_sample = False, return_full_text = False, clean_up_tokenization_spaces = False)
    raw_output = response[0]["generated_text"]
    

    predicted_label = clean_predictions(raw_output)
    few_shot_predictions.append(predicted_label)
    few_shot_true_labels.append(y_test.iloc[i])
    
    # print(i+1, "of", len(X_test))
    # print(raw_output)
    # print(predicted_label)
    # print(y_test.iloc[i])
    
print(f1_score(few_shot_true_labels, few_shot_predictions, labels=party_labels,  average="macro", zero_division=0))
print(classification_report(few_shot_true_labels, few_shot_predictions, labels = party_labels, zero_division=0))

